CI: run "Publish COSMIC release" with tag push
- Workflow is executed with event 'push tags'
- Add step to validate tag as 'a.b.c'
- Publish official release (no draft).

Signed-off-by: Laurent Cheylus <foxy@free.fr>

diff --git a/.github/workflows/release-cosmic.yml b/.github/workflows/release-cosmic.yml
--- a/.github/workflows/release-cosmic.yml
+++ b/.github/workflows/release-cosmic.yml
@@ -1,10 +1,12 @@
 name: Publish COSMIC release
 
-# TODO: run workflow on "push tags"
-on: workflow_dispatch
+on:
+  push:
+    tags:
+      - "*.*.*"
 
 env:
-  VERSION: 1.4.0
+  VERSION: ${{ github.ref_name }}
 
 permissions: {}
 
@@ -14,8 +16,21 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  valid-version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate version
+        run: |
+          if [[ "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid version: ${{ env.VERSION }}"
+          else
+            echo "Invalid tag for version: ${{ env.VERSION }}"
+            exit 1
+          fi
+
   build:
     name: Build ${{ matrix.component }}
+    needs: valid-version
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -121,7 +136,6 @@ jobs:
 
             printf '### debian/rules file\n%s\n' "$(cat debian/rules)"
 
-            # TODO: Commit debian/changelog after release to keep changes
             echo "::group::Update changelog"
             current_version=$(dpkg-parsechangelog --show-field Version)
             printf "current_version = %s\n" "${current_version}"
@@ -163,6 +177,7 @@ jobs:
             echo "::endgroup::"
           fi
 
+      # TODO: add case to upload pop-launcher-system76-power package (pop-launcher)
       - name: Upload package
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
         with:
@@ -171,7 +186,7 @@ jobs:
           retention-days: 1
           archive: false
 
-          # Special case for cosmic-greeter component: 2 packages built
+      # Special case for cosmic-greeter component: 2 packages built
       - name: Upload cosmic-greeter-daemon
         if: ${{ matrix.component == 'cosmic-greeter' }}
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
@@ -191,6 +206,7 @@ jobs:
 
   build-apps:
     name: Build ${{ matrix.app }}
+    needs: valid-version
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -267,17 +283,16 @@ jobs:
       - name: Publish release
         uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  #v3.0.2
         with:
-          draft: true
           files: "*.deb"
           fail_on_unmatched_files: true
-          make_latest: false
+          make_latest: true
           name: "Release for COSMIC Epoch ${{ env.VERSION }}"
           body: >
-            Debian packages built on testing to install COSMIC Desktop Environment
+            Debian testing packages to install COSMIC Desktop Environment
             [version epoch-${{ env.VERSION }}](https://github.com/pop-os/cosmic-epoch/releases/tag/epoch-${{ env.VERSION }})
 
 
-            Contains all the components unecessary to install COSMIC DE and optional applications
+            Contains all the components necessary to install COSMIC DE and optional applications
             (Edit, Files, Monitor, Player, Store and Term).
 
   commit-changelog:
@@ -313,5 +328,5 @@ jobs:
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add "changelog"
-          git commit -m "Update changelog for COSMIC components - version ${{ env.VERSION }}"
+          git commit -m "Update changelog for COSMIC components after release version ${{ env.VERSION }}"
           git push
